#jwt:
  #secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'


server:
  port: 8081
#  error:
#    whitelabel:
#      enabled: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userapp #change this to your database url
    password: password #change this to your database username
    username: username #change this to your database password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
 # mvc:
  #  throw-exception-if-no-handler-found: true
  #resources:
  #  add-mappings: false